// Generated by CoffeeScript 1.6.3
(function() {
  jQuery(function() {
    $('.ui.sidebar').sidebar({
      overlay: true
    });
    $('body').click(function(e) {
      if ($('.ui.sidebar').sidebar('is open')) {
        return $('.ui.sidebar').sidebar('hide');
      }
    });
    return $('.sidebar-toggle').click(function(e) {
      e.preventDefault();
      e.stopPropagation();
      return $('.ui.sidebar').sidebar('show');
    });
  });

}).call(this);
